### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by DavutOzcan87** [adyen-examples/adyen-java-spark-online-payments#3]
When i set the config and do gradle run it forwards to 

http://localhost:8080/auth/
and gives error
404 Not found

**Comment by tddouglas** [comment]
What URL are you attempting to access which forwards the request to http://localhost:8080/auth/? http://localhost:8080 should be your first stop and should not redirect

Also, I want to make sure you're using the gradle wrapper command `./graldew run`, not base gradle

**Comment by tddouglas** [comment]
Closing due to lack of info.
