### ISSUE TITLE
ApiError Unable To Process

### ISSUE THREAD

**Issue by lupenkoc** [adyen-examples/adyen-java-spark-online-payments#4]
I am receiving ApiError 904 when completing payment with 3ds1 - https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1/web-component#post-paymentdetails3ds
`ApiException{error=class ApiError {
    status: 500
    errorCode: 904
    message: Unable To Process
    errorType: internal
    pspReference: 851609774711826A
    invalidFields: null
}`

Test card:
American Express | 3451 7792 5488 348 | International | 03 | 2030 | 7373

What is the issue?
Thanks

**Comment by tddouglas** [comment]
Hello, this was a temporary issue with our TEST environment APIs which was resolved shortly after.
Attempting the same payment again should result in a successful auth.
